### ISSUE TITLE
Subsample scatterplots when beyond a set number of points

### ISSUE THREAD

**Issue by shihabdider** [mskilab-org/case-report#6]
**Is your feature request related to a problem? Please describe.**
Currently, the scatterplots appear to render every single point within the view window. Thus, when the user is fully zoomed out, all points are rendered. This leads to a loss in performance. 

**Describe the solution you'd like**
Set a fixed threshold for maximum number of points (e.g 20 thousand). Then subsample whenever the number of points is greater than this threshold to reduce the number of points rendered until it meets this threshold. 

Here's an implementation using Fisher-Yates shuffling (can use something else if it's better/faster, this is just a first approximation):

```js
function subsamplePoints(points, threshold = 20000) {
  if (points.length <= threshold) {
    return points;
  }

  // Use Fisher-Yates shuffle to efficiently get random sample
  let result = [];
  const totalPoints = points.length;
  
  const indices = Array.from(Array(totalPoints).keys());
  
  for (let i = totalPoints - 1; i > totalPoints - threshold - 1; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [indices[i], indices[j]] = [indices[j], indices[i]]; // swap
  }
  
  for (let k = 0; k < threshold; k++) {
    result.push(points[indices[k]]);
  }

  return result;
}

// usage:
const pointsArray = [...Array(30000).keys()]; 
const maxThreshold = 20000;
const reducedPoints = subsamplePoints(pointsArray, maxThreshold);
console.log(`after subsampling: ${reducedPoints.length}`);
```

**Additional context**
The subsampling should probably be debounced (with an appropriate loading indicator to give UI feedback to the user) to the user zooming in/out. We can also play around with the threshold for optimal smoothing and performance.

**Comment by xanthopoulakis** [comment]
I understand the idea pitched here, downsampling may have some obvious benefits, yet this is more of a political rather than a technical choice, a debate that goes back to the early ages of gGnome.js. The very first scatterplot I built was actually employing such a downsampling scheme, to ensure the visual elements on the screen stay within reason. Marcin then turned down the idea, wishing to have the full spectum of all points belonging in the dataset loaded on the screen - this is how we got into the Apache Arrow files with the 200k+ datapoints.

The latest implementation of the scatterplot uses the GPU for rendering via webgl such great numbers of datapoints **and** ensuring a smooth zoom in/out behavior. I believe that dowsampling the scatterplots needs to be aligned with Marcin and the rest of the lab fellows, as it is fundamental change in how we manage big data scatterplots.

**Comment by shihabdider** [comment]
Ah, right, I forgot that the points were rendered via GPU. The issue might be on my (integrated gpu) side then. OK let's table this for now. The other reason to not render all points is smoothing, but technically the rebinning should have taken care of that.
